url: "minhtrandev.com"                                          # The base hostname & protocol for your site, e.g. http://example.com
baseurl: ""                                                     # The subpath of your site, e.g. /blog
title: "Home"                                                   # The name of your site, e.g. ACME Corp.
lang: en-EN                                                     # The language of your site, e.g. en-EN
theme_custom: white-grey-pacifico                               # The name of your theme, e.g. gree-white, gray-white, indigo-white, indigo-white-pacifico, etc.
theme_name_background: false                                    # The name of your background image (keep false value if you don't want background image), e.g. bg
theme_extension_background: png                                 # The extension name of your background file, e.g. png
author: Minh Tran                                               # The name of author, show in the home page "Hello, I'm *author*" and SEO.
description: &description Software Engineer, .NET               # Description for SEO.
tagline: *description
title_intro:                                                    # Overwrite "Hello, I'm *author*", keep empty for don't overwrite.
skill_separator: "|"                                            # The separator symbol to your skill at home page.
title_platforms: Connect with me on                             # Keep empty for don't show title on platforms icon.

# Build settings
plugins:
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
