version: '3'

services:
    jekyll:
        image: younglook/jekyll-arm64:latest
        command: jekyll serve --watch --incremental --livereload --drafts --force_polling --verbose
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll
